### ISSUE TITLE
你好，我在执行您的代码时遇到一个无法解决的问题，想问一下您又什么解决方案吗？

### ISSUE THREAD

**Issue by Magic-pirate** [LanXiu-0523/Fault-diagnosis-of-rolling-bearing-based-on-whvg-and-GCN_GIN#2]
![image](https://user-images.githubusercontent.com/90440419/186759717-1c2950b3-f9b3-4580-8093-a7c4b8a3d790.png)

**Comment by LanXiu0523** [comment]
打个断点调试下看看？我没遇到过这类问题，或许是包版本不匹配导致的？
