### ISSUE TITLE
Hello~

### ISSUE THREAD

**Issue by XMAHA** [LanXiu-0523/Fault-diagnosis-of-rolling-bearing-based-on-whvg-and-GCN_GIN#5]
您好，我是该论文的作者之一，非常感谢您关注到我们的工作和对论文代码的复现，希望您可以对论文加以标注，明确是引用他人论文并复现，已有其他学者发邮件询问代码是否是我们上传等等，因该论文代码我们还没有计划开源，为避免麻烦，烦请尽快修改标注，再次感谢。

**Comment by LanXiu0523** [comment]
收到，我已注明复现论文和引用来源，非常抱歉给您和您的团队带来不便。

**Comment by ywlaw** [comment]
Hi LanXiu, I think you implemented GCN, but the original authors used GIN (despite the term "GCN" in the title of their paper). Is my observation correct?
