### ISSUE TITLE
请教您一个问题，当我把类别数调多了，准确率达不到了，该怎么办

### ISSUE THREAD

**Issue by GGGsp** [LanXiu-0523/Fault-diagnosis-of-rolling-bearing-based-on-whvg-and-GCN_GIN#6]
![微信图片_20230626143053](https://github.com/LanXiu-0523/WHVG_GCN/assets/111620751/66ecfe3e-2097-4de5-8ab4-5f65c67afa24)
  

我将cwru数据9类故障分类 加健康一共10类 10个标签 然后进行训练 准确率上不去

![image](https://github.com/LanXiu-0523/WHVG_GCN/assets/111620751/45a7d30a-5b01-4b24-9417-81f27f939e2e)

**Comment by LanXiu0523** [comment]
确实会这样，因为IR，OR，BA是三类不同的错误类型，其之间容易相互分类且容易与Normal分类。但IR0，IR1，IR2是同一类错误中不同的细分，分类难度较大，建议归到一个错误类型中和其他错误类型与健康组做分类。
